### ISSUE TITLE
[Doc] README updates

### ISSUE THREAD

**Issue by maitri-vv** [shruti-sen2004/BudgetBuddy#10]
Hey! Can i put a proper README for this Repo since it would help people participating in Hacktoberfest know about it.

**Comment by shruti-sen2004** [comment]
Hi @maitri-vv ,
Thank you for your suggestion. As the project is still undergoing a lot of changes I am currently not able to put up a proper README. Once the updates are done I will surely do the same.
Best regards,
Shruti
