### ISSUE TITLE
Filter for transactions

### ISSUE THREAD

**Issue by R0Y15** [shruti-sen2004/BudgetBuddy#12]
I'd really love to contribute to the project. I plan to add a filter option to seperate expenses and incomes in the transaction history. 
please assign this problem to me under hacktoberfest Label.

**Comment by shruti-sen2004** [comment]
Hi @R0Y15 ,
Thank you for showing interest in my repository. I really liked your idea of adding the filter feature to the history section. Thus I am assigning you this issue. As I can see you have already made a PR so give me some time I would review your changes and follow up soon.
Best regards,
Shruti
