### ISSUE TITLE
aligning "Budget Buddy" logo to the center

### ISSUE THREAD

**Issue by GauravChinavle** [shruti-sen2004/BudgetBuddy#13]
Logo is not center aligned.
Please assign this issue to me under hacktoberfest

Screenshot:
<img width="711" alt="Screenshot 2024-10-12 at 5 11 29 PM" src="https://github.com/user-attachments/assets/1d51a554-1cf0-4ac5-8ab4-05f85f68394d">

**Comment by shruti-sen2004** [comment]
Hi @GauravChinavle ,
Thank you for showing interest in my repository. The logo alignment looks quite right to me, and I am not looking forward to changing it. 
Best regards,
Shruti
