### ISSUE TITLE
[Feature]: Dark mode enabled for bettter User Experience

### ISSUE THREAD

**Issue by yazdanhaider** [shruti-sen2004/BudgetBuddy#18]
I want to work on the dark mode feature for better UX. Also making you sure transition will be smooth between light and dark modes and all the other fuctionalites will be remain unaffected!!!

Please assign me this issue and also add hacktober-accepted label into this.

**Comment by yazdanhaider** [comment]
Please assign me the as i have already worked on it.

# Screenshot
<img width="1369" alt="Screenshot 2024-10-18 at 3 30 44 PM" src="https://github.com/user-attachments/assets/c1941c77-66e2-4073-bb48-48e60b43896e">
<img width="1369" alt="Screenshot 2024-10-18 at 3 30 53 PM" src="https://github.com/user-attachments/assets/c56fb3a2-a5a2-4069-92a2-0fdb995254ef">

**Comment by shruti-sen2004** [comment]
Hi @yazdanhaider,
Thank you for showing interest in my repo! The feature idea looks good to me, and you can definitely start working on it. However, I would suggest focusing on improving the current layout of the project for implementing this feature. 
Best regards,
Shruti

**Comment by yazdanhaider** [comment]
> Hi @yazdanhaider, Thank you for showing interest in my repo! The feature idea looks good to me, and you can definitely start working on it. However, I would suggest focusing on improving the current layout of the project for implementing this feature. If you agree to work on this please let me know and I would assign the issue to you. Best regards, Shruti

Heyy @shruti-sen2004 Thank you for considering my feature idea. However I don’t feel that the current UI is suitable, so I’m unable to proceed with this feature.

**Comment by shruti-sen2004** [comment]
> > Hi @yazdanhaider, Thank you for showing interest in my repo! The feature idea looks good to me, and you can definitely start working on it. However, I would suggest focusing on improving the current layout of the project for implementing this feature. If you agree to work on this please let me know and I would assign the issue to you. Best regards, Shruti
> 
> Heyy @shruti-sen2004 Thank you for considering my feature idea. However I don’t feel that the current UI is suitable, so I’m unable to proceed with this feature.

Okey 😊. But in future if you wish to contribute on more features or bug fixes you are more than welcome.
Regards,
Shruti
