### ISSUE TITLE
Enhance Overall UI/UX with CSS

### ISSUE THREAD

**Issue by KrishnaSaxena108** [shruti-sen2004/BudgetBuddy#4]
Hi @shruti-sen2004 , I want to enhance the overall layout and styling of this website and make it responsive.
Kindly, Assign me this issue under HacktoberFest 2024.
Thankyou

**Comment by shruti-sen2004** [comment]
Hi @KrishnaSaxena108 ,
Thank you for your interest in enhancing the layout and styling of the website. However, at the moment, I am not looking for any styling updates. I appreciate your initiative..
Best regards,
Shruti
