### ISSUE TITLE
Make use of React/ Next JS to enhance look and feel

### ISSUE THREAD

**Issue by SAQLAINAP** [shruti-sen2004/BudgetBuddy#5]
Use React/Next JS to make the site better and also add a better looking UI using bootstrap or tailwind. Please assign me this, i can build the same quickly.

**Comment by shruti-sen2004** [comment]
Hi @SAQLAINAP  ,
Thank you for your interest in my repository. However, at the moment, I am not looking for any styling updates. I appreciate your initiative, If you're interested, you're welcome to contribute by working on bug fixes or feature enhancements instead. 
Best regards,
Shruti
