### ISSUE TITLE
Transaction deletion button occupies whitespace by default

### ISSUE THREAD

**Issue by x0rzavi** [shruti-sen2004/BudgetBuddy#7]
**Description**
The delete button in the expenses history should appear only when history item is hovered over and should not occupy any whitespace. Additionally, the amount item should shift to the left to make space for the delete button when it appears.

**Styling proposals**
1. Current behavior
![Screenshot 2024-10-10 102617](https://github.com/user-attachments/assets/f45bf349-f6e7-4103-9ffa-10e68ad2f339)
![Screenshot 2024-10-10 102625](https://github.com/user-attachments/assets/8ebbac49-e3d2-40bd-b4a8-ee1b0de39826)

2. Expected behavior
![Screenshot 2024-10-10 101335](https://github.com/user-attachments/assets/daa5fd13-ace8-44bb-b5f5-254171d72b00)
![Screenshot 2024-10-10 101355](https://github.com/user-attachments/assets/c4741c9f-c7f9-41ad-88da-f3fe07e923e8)

Could you please assign this issue to me?

**Comment by shruti-sen2004** [comment]
Okey, sounds good. The issue has been assigned to you. You may now start working on the feature.
